SELECT USER
FROM DUAL;

-- 1. ROLE 테이블 생성
CREATE TABLE ROLE
( ROLE_ID       NUMBER          NOT NULL
, ROLE_NAME     VARCHAR2(10)    NOT NULL
, CONSTRAINT    ROLE_ROLE_ID_PK PRIMARY KEY(ROLE_ID)
, CONSTRAINT    ROLE_ROLE_NAME_UK	UNIQUE(ROLE_NAME)
);

-- 2. USER_STATUS 테이블 생성
CREATE TABLE USER_STATUS
( STATUS_ID     NUMBER          NOT NULL
, STATUS_NAME   VARCHAR2(50)    NOT NULL
, CONSTRAINT    STATUS_STATUS_ID_PK PRIMARY KEY(STATUS_ID)
, CONSTRAINT    STATUS_STATUS_NAME_UK   UNIQUE(STATUS_NAME)
);

-- 3. STATUS 테이블 생성
CREATE TABLE BOOK_STATUS
( BOOK_STATUS_ID    NUMBER          NOT NULL
, BOOK_STATUS_NAME  VARCHAR2(50)    NOT NULL
, CONSTRAINT BOOK_STATUS_ID_PK  PRIMARY KEY(BOOK_STATUS_ID)
, CONSTRAINT B_STATUS_B_STATUS_NAME_UK    UNIQUE(BOOK_STATUS_NAME)
);

-- 4. PUBLISHERS 테이블 생성
CREATE TABLE PUBLISHERS
( PUB_ID    NUMBER          NOT NULL
, PUB_NAME  VARCHAR2(30)    NOT NULL
, CONSTRAINT PUBLISHERS_PUB_ID_PK   PRIMARY KEY(PUB_ID)   
, CONSTRAINT PUBLISHERS_PUB_NAME_UK	UNIQUE(PUB_NAME)
);

-- 5. AUTHORS 테이블 생성
CREATE TABLE AUTHORS
( AUTHOR_ID     NUMBER          NOT NULL
, AUTHOR_NAME   VARCHAR2(30)    NOT NULL
, CONSTRAINT AUTHORS_AUTHOR_ID_PK    PRIMARY KEY(AUTHOR_ID)
, CONSTRAINT AUTHORS_AUTHOR_NAME_UK	 UNIQUE(AUTHOR_NAME)
);

-- 6. CATEGORIES 테이블 생성
CREATE TABLE CATEGORIES
( CAT_ID    VARCHAR2(3)          NOT NULL
, CAT_NAME  VARCHAR2(50)    NOT NULL
, PARENT_ID VARCHAR2(3)       
, CONSTRAINT CATEGORIES_CAT_ID_PK PRIMARY KEY(CAT_ID)
, CONSTRAINT CATEGORIES_CAT_NAME_UK UNIQUE(CAT_NAME)
, CONSTRAINT CATEGORIES_CAT_PARENT_ID_FK FOREIGN KEY(PARENT_ID)
        REFERENCES CATEGORIES(CAT_ID)
);

-- 7. LOAN_EVENTS 테이블 생성
CREATE TABLE LOAN_EVENTS
( EVENT_ID          NUMBER          NOT NULL
, EVENT_NAME        VARCHAR2(30)    NOT NULL
, START_DATE        DATE            NOT NULL   
, END_DATE          DATE            NOT NULL
, MAX_LOAN_LIMIT    NUMBER(2)       NOT NULL
, CONSTRAINT LOAN_EVENTS_EVENT_ID_PK PRIMARY KEY(EVENT_ID)
);

-- 8. USERS 테이블 생성
CREATE TABLE USERS
( USER_ID       NUMBER          NOT NULL
, LOGIN_ID      VARCHAR2(30)    NOT NULL
, PW            VARCHAR2(30)    NOT NULL
, NAME          VARCHAR2(20)    NOT NULL
, BIRTH         DATE            NOT NULL
, GENDER        CHAR(1)         NOT NULL
, PHONE         VARCHAR2(13)    NOT NULL
, EMAIL         VARCHAR2(50)
, STATUS_ID     NUMBER          NOT NULL
, ROLE_ID       NUMBER          NOT NULL
, CREATED_AT    DATE     DEFAULT SYSDATE NOT NULL
, PENALTY_EDATE DATE    
, CONSTRAINT   USERS_USER_ID_PK PRIMARY KEY(USER_ID)
, CONSTRAINT   USERS_LOGIN_ID_UK    UNIQUE(LOGIN_ID)
, CONSTRAINT   USERS_EMAIL_UK       UNIQUE(EMAIL)	
, CONSTRAINT   USERS_STATUS_ID_FK   FOREIGN KEY(STATUS_ID)
            REFERENCES USER_STATUS(STATUS_ID)
, CONSTRAINT   USERS_ROLE_ID_FK   FOREIGN KEY(ROLE_ID)
            REFERENCES ROLE(ROLE_ID)            
);

-- 9. BOOK_INFO 테이블 생성
CREATE TABLE BOOK_INFO
( ISBN      VARCHAR2(20)        NOT NULL
, TITLE     VARCHAR2(100)   NOT NULL
, PUB_ID    NUMBER          NOT NULL
, CAT_ID    VARCHAR2(3)          NOT NULL
, CONSTRAINT BOOK_INFO_ISBN_PK PRIMARY KEY(ISBN)
, CONSTRAINT BOOK_INFO_PUB_ID_FK FOREIGN KEY(PUB_ID)
            REFERENCES PUBLISHERS(PUB_ID)
, CONSTRAINT BOOK_INFO_CAT_ID_FK FOREIGN KEY(CAT_ID)
            REFERENCES CATEGORIES(CAT_ID)
);

-- 10. BOOK_COPY 테이블 생성
CREATE TABLE BOOK_COPY
( BOOK_ID           NUMBER      NOT NULL
, ISBN              VARCHAR2(20)    NOT NULL
, BOOK_STATUS_ID    NUMBER      NOT NULL
, CREATED_AT        DATE        DEFAULT SYSDATE NOT NULL
, CONSTRAINT BOOK_COPY_BOOK_ID_PK PRIMARY KEY(BOOK_ID)
, CONSTRAINT BOOK_COPY_ISBN_FK FOREIGN KEY(ISBN)
            REFERENCES BOOK_INFO(ISBN)
, CONSTRAINT BOOK_COPY_BOOK_STATUS_ID_FK FOREIGN KEY(BOOK_STATUS_ID)
            REFERENCES BOOK_STATUS(BOOK_STATUS_ID)
);

-- 11. CONTRIBUTOR 테이블 생성
CREATE TABLE CONTRIBUTOR
( CONTRIBUTOR_ID    NUMBER      NOT NULL
, ISBN              VARCHAR2(20)    NOT NULL
, AUTHOR_ID         NUMBER      NOT NULL
, AUTHOR_ORDER      NUMBER(3)   
, CONSTRAINT CONTRIBUTOR_CONTRIBUTOR_ID_PK PRIMARY KEY(CONTRIBUTOR_ID)
, CONSTRAINT CONTRIBUTOR_ISBN_FK FOREIGN KEY(ISBN)
            REFERENCES BOOK_INFO(ISBN)
, CONSTRAINT CONTRIBUTOR_AUTHOR_ID_FK FOREIGN KEY(AUTHOR_ID)
            REFERENCES AUTHORS(AUTHOR_ID)
, CONSTRAINT CONTRIBUTOR_ISBN_AUT_ID_UK UNIQUE(ISBN, AUTHOR_ID)
, CONSTRAINT CONTRIBUTOR_ISBN_AUT_ORDER_UK	UNIQUE(ISBN, AUTHOR_ORDER)

);

-- 12. LOANS 테이블 생성
CREATE TABLE LOANS
( LOAN_ID       NUMBER      NOT NULL
, BOOK_ID       NUMBER      NOT NULL
, USER_ID       NUMBER      NOT NULL
, LOAN_DATE     DATE        DEFAULT SYSDATE NOT NULL
, DUE_DATE      DATE        DEFAULT SYSDATE+14  NOT NULL
, RETURN_DATE   DATE    
, EXT_COUNT     NUMBER(1)   NOT NULL
, CONSTRAINT LOANS_LOAN_ID_PK PRIMARY KEY(LOAN_ID)
, CONSTRAINT LOANS_BOOK_ID_FK FOREIGN KEY(BOOK_ID)
            REFERENCES BOOK_COPY(BOOK_ID)
, CONSTRAINT LOANS_USER_ID_FK FOREIGN KEY(USER_ID)
            REFERENCES USERS(USER_ID)
, CONSTRAINT LOANS_EXT_COUNT_CK CHECK(EXT_COUNT IN (0,1))
);


--------------------------------------------------------------------------------
--[시퀀스 생성]
--------------------------------------------------------------------------------

CREATE SEQUENCE SEQ_ROLE
START WITH 1
NOCACHE;

CREATE SEQUENCE SEQ_USER_STATUS
START WITH 1
NOCACHE;

CREATE SEQUENCE SEQ_BOOK_STATUS
START WITH 1
NOCACHE;

CREATE SEQUENCE SEQ_PUBlISHER
START WITH 1
NOCACHE;

CREATE SEQUENCE SEQ_AUTHOR
START WITH 1
NOCACHE;



CREATE SEQUENCE SEQ_LOAN_EVENT
START WITH 1
NOCACHE;

CREATE SEQUENCE SEQ_USER
START WITH 1
NOCACHE;

CREATE SEQUENCE SEQ_BOOK_COPY
START WITH 1
NOCACHE;

CREATE SEQUENCE SEQ_CONTRIBUTOR
START WITH 1
NOCACHE;

CREATE SEQUENCE SEQ_LOAN
START WITH 1
NOCACHE;



--------------------------------------------------------------------------------
--[기본데이터 생성]
--------------------------------------------------------------------------------
INSERT INTO ROLE(ROLE_ID, ROLE_NAME) VALUES(SEQ_ROLE.NEXTVAL, '관리자');
INSERT INTO ROLE(ROLE_ID, ROLE_NAME) VALUES(SEQ_ROLE.NEXTVAL, '사서');
INSERT INTO ROLE(ROLE_ID, ROLE_NAME) VALUES(SEQ_ROLE.NEXTVAL, '회원');

SELECT *
FROM ROLE;

--==>>
/*
1	관리자
2	사서
3	회원
*/

INSERT INTO USER_STATUS(STATUS_ID, STATUS_NAME) VALUES(SEQ_USER_STATUS.NEXTVAL, '정상');
INSERT INTO USER_STATUS(STATUS_ID, STATUS_NAME) VALUES(SEQ_USER_STATUS.NEXTVAL, '연체정지');
INSERT INTO USER_STATUS(STATUS_ID, STATUS_NAME) VALUES(SEQ_USER_STATUS.NEXTVAL, '이용정지');

SELECT *
FROM USER_STATUS;

--==>>
/*
1	정상
2	연체정지
3	이용정지
*/
INSERT INTO BOOK_STATUS(BOOK_STATUS_ID, BOOK_STATUS_NAME) VALUES(SEQ_BOOK_STATUS.NEXTVAL, '대출가능');
INSERT INTO BOOK_STATUS(BOOK_STATUS_ID, BOOK_STATUS_NAME) VALUES(SEQ_BOOK_STATUS.NEXTVAL, '대출중');
INSERT INTO BOOK_STATUS(BOOK_STATUS_ID, BOOK_STATUS_NAME) VALUES(SEQ_BOOK_STATUS.NEXTVAL, '이용불가');


SELECT *
FROM BOOK_STATUS;
--==>>
/*
1	대출가능
2	대출중
3	이용불가
*/

INSERT INTO CATEGORIES(CAT_ID, CAT_NAME, PARENT_ID) VALUES('000', '총류', NULL); 
INSERT INTO CATEGORIES(CAT_ID, CAT_NAME, PARENT_ID) VALUES('010', '도서학·서지학', '000'); 
INSERT INTO CATEGORIES(CAT_ID, CAT_NAME, PARENT_ID) VALUES('020', '문헌정보학', '000'); 
INSERT INTO CATEGORIES(CAT_ID, CAT_NAME, PARENT_ID) VALUES('030', '백과사전', '000'); 
INSERT INTO CATEGORIES(CAT_ID, CAT_NAME, PARENT_ID) VALUES('040', '강연집·수필집', '000'); 
INSERT INTO CATEGORIES(CAT_ID, CAT_NAME, PARENT_ID) VALUES('050', '연속간행물', '000'); 
INSERT INTO CATEGORIES(CAT_ID, CAT_NAME, PARENT_ID) VALUES('060', '학회·단체', '000'); 
INSERT INTO CATEGORIES(CAT_ID, CAT_NAME, PARENT_ID) VALUES('070', '신문·언론', '000'); 
INSERT INTO CATEGORIES(CAT_ID, CAT_NAME, PARENT_ID) VALUES('080', '전집·총서', '000'); 
INSERT INTO CATEGORIES(CAT_ID, CAT_NAME, PARENT_ID) VALUES('090', '향토자료', '000'); 

INSERT INTO CATEGORIES(CAT_ID, CAT_NAME, PARENT_ID) VALUES('100', '철학', NULL); 
INSERT INTO CATEGORIES(CAT_ID, CAT_NAME, PARENT_ID) VALUES('110', '형이상학', '100'); 
INSERT INTO CATEGORIES(CAT_ID, CAT_NAME, PARENT_ID) VALUES('120', '인식론·인과론·인간학', '100'); 
INSERT INTO CATEGORIES(CAT_ID, CAT_NAME, PARENT_ID) VALUES('130', '철학의 체계', '100'); 
INSERT INTO CATEGORIES(CAT_ID, CAT_NAME, PARENT_ID) VALUES('140', '경학', '100'); 
INSERT INTO CATEGORIES(CAT_ID, CAT_NAME, PARENT_ID) VALUES('150', '동양철학·사상', '100'); 
INSERT INTO CATEGORIES(CAT_ID, CAT_NAME, PARENT_ID) VALUES('160', '서양철학', '100'); 
INSERT INTO CATEGORIES(CAT_ID, CAT_NAME, PARENT_ID) VALUES('170', '논리학', '100'); 
INSERT INTO CATEGORIES(CAT_ID, CAT_NAME, PARENT_ID) VALUES('180', '심리학', '100'); 
INSERT INTO CATEGORIES(CAT_ID, CAT_NAME, PARENT_ID) VALUES('190', '윤리학·도덕철학', '100'); 

INSERT INTO CATEGORIES(CAT_ID, CAT_NAME, PARENT_ID) VALUES('200', '종교', NULL); 
INSERT INTO CATEGORIES(CAT_ID, CAT_NAME, PARENT_ID) VALUES('210', '비교종료', '200'); 
INSERT INTO CATEGORIES(CAT_ID, CAT_NAME, PARENT_ID) VALUES('220', '불교', '200'); 
INSERT INTO CATEGORIES(CAT_ID, CAT_NAME, PARENT_ID) VALUES('230', '기독교', '200'); 
INSERT INTO CATEGORIES(CAT_ID, CAT_NAME, PARENT_ID) VALUES('240', '도교', '200'); 
INSERT INTO CATEGORIES(CAT_ID, CAT_NAME, PARENT_ID) VALUES('250', '천도교', '200'); 
INSERT INTO CATEGORIES(CAT_ID, CAT_NAME, PARENT_ID) VALUES('260', '신도', '200'); 
INSERT INTO CATEGORIES(CAT_ID, CAT_NAME, PARENT_ID) VALUES('270', '힌두교·브라만교', '200'); 
INSERT INTO CATEGORIES(CAT_ID, CAT_NAME, PARENT_ID) VALUES('280', '이슬람교(회교)', '200'); 
INSERT INTO CATEGORIES(CAT_ID, CAT_NAME, PARENT_ID) VALUES('290', '기타 제종교', '200'); 

INSERT INTO CATEGORIES(CAT_ID, CAT_NAME, PARENT_ID) VALUES('300', '사회과학', NULL); 
INSERT INTO CATEGORIES(CAT_ID, CAT_NAME, PARENT_ID) VALUES('310', '통계학', '300'); 
INSERT INTO CATEGORIES(CAT_ID, CAT_NAME, PARENT_ID) VALUES('320', '경제학', '300'); 
INSERT INTO CATEGORIES(CAT_ID, CAT_NAME, PARENT_ID) VALUES('330', '사회학·사회문제', '300'); 
INSERT INTO CATEGORIES(CAT_ID, CAT_NAME, PARENT_ID) VALUES('340', '정치학', '300'); 
INSERT INTO CATEGORIES(CAT_ID, CAT_NAME, PARENT_ID) VALUES('350', '행정학', '300'); 
INSERT INTO CATEGORIES(CAT_ID, CAT_NAME, PARENT_ID) VALUES('360', '법학', '300'); 
INSERT INTO CATEGORIES(CAT_ID, CAT_NAME, PARENT_ID) VALUES('370', '교육학', '300'); 
INSERT INTO CATEGORIES(CAT_ID, CAT_NAME, PARENT_ID) VALUES('380', '풍속·예절·민속학', '300'); 
INSERT INTO CATEGORIES(CAT_ID, CAT_NAME, PARENT_ID) VALUES('390', '국방·군사학', '300'); 

INSERT INTO CATEGORIES(CAT_ID, CAT_NAME, PARENT_ID) VALUES('400', '자연과학', NULL); 
INSERT INTO CATEGORIES(CAT_ID, CAT_NAME, PARENT_ID) VALUES('410', '수학', '400'); 
INSERT INTO CATEGORIES(CAT_ID, CAT_NAME, PARENT_ID) VALUES('420', '물리학', '400'); 
INSERT INTO CATEGORIES(CAT_ID, CAT_NAME, PARENT_ID) VALUES('430', '화학', '400'); 
INSERT INTO CATEGORIES(CAT_ID, CAT_NAME, PARENT_ID) VALUES('440', '천문학', '400'); 
INSERT INTO CATEGORIES(CAT_ID, CAT_NAME, PARENT_ID) VALUES('450', '지학', '400'); 
INSERT INTO CATEGORIES(CAT_ID, CAT_NAME, PARENT_ID) VALUES('460', '광물학', '400'); 
INSERT INTO CATEGORIES(CAT_ID, CAT_NAME, PARENT_ID) VALUES('470', '생명과학', '400'); 
INSERT INTO CATEGORIES(CAT_ID, CAT_NAME, PARENT_ID) VALUES('480', '식물학', '400'); 
INSERT INTO CATEGORIES(CAT_ID, CAT_NAME, PARENT_ID) VALUES('490', '동물학', '400');

INSERT INTO CATEGORIES(CAT_ID, CAT_NAME, PARENT_ID) VALUES('500', '기술과학', NULL); 
INSERT INTO CATEGORIES(CAT_ID, CAT_NAME, PARENT_ID) VALUES('510', '의학', '500'); 
INSERT INTO CATEGORIES(CAT_ID, CAT_NAME, PARENT_ID) VALUES('520', '농업·농학', '500'); 
INSERT INTO CATEGORIES(CAT_ID, CAT_NAME, PARENT_ID) VALUES('530', '공학·공업일반', '500'); 
INSERT INTO CATEGORIES(CAT_ID, CAT_NAME, PARENT_ID) VALUES('540', '건축공학', '500'); 
INSERT INTO CATEGORIES(CAT_ID, CAT_NAME, PARENT_ID) VALUES('550', '기계공학', '500'); 
INSERT INTO CATEGORIES(CAT_ID, CAT_NAME, PARENT_ID) VALUES('560', '전기·전자공학', '500'); 
INSERT INTO CATEGORIES(CAT_ID, CAT_NAME, PARENT_ID) VALUES('570', '화학공학', '500'); 
INSERT INTO CATEGORIES(CAT_ID, CAT_NAME, PARENT_ID) VALUES('580', '제조업', '500'); 
INSERT INTO CATEGORIES(CAT_ID, CAT_NAME, PARENT_ID) VALUES('590', '생활학', '500'); 

INSERT INTO CATEGORIES(CAT_ID, CAT_NAME, PARENT_ID) VALUES('600', '예술', NULL); 
INSERT INTO CATEGORIES(CAT_ID, CAT_NAME, PARENT_ID) VALUES('610', '건축물', '600'); 
INSERT INTO CATEGORIES(CAT_ID, CAT_NAME, PARENT_ID) VALUES('620', '조각·조형예술', '600'); 
INSERT INTO CATEGORIES(CAT_ID, CAT_NAME, PARENT_ID) VALUES('630', '공예·장식미술', '600'); 
INSERT INTO CATEGORIES(CAT_ID, CAT_NAME, PARENT_ID) VALUES('640', '서예', '600'); 
INSERT INTO CATEGORIES(CAT_ID, CAT_NAME, PARENT_ID) VALUES('650', '회화·도화', '600'); 
INSERT INTO CATEGORIES(CAT_ID, CAT_NAME, PARENT_ID) VALUES('660', '사진예술', '600'); 
INSERT INTO CATEGORIES(CAT_ID, CAT_NAME, PARENT_ID) VALUES('670', '음악', '600'); 
INSERT INTO CATEGORIES(CAT_ID, CAT_NAME, PARENT_ID) VALUES('680', '공연예술·매체예술', '600'); 
INSERT INTO CATEGORIES(CAT_ID, CAT_NAME, PARENT_ID) VALUES('690', '오락·스포츠', '600'); 

INSERT INTO CATEGORIES(CAT_ID, CAT_NAME, PARENT_ID) VALUES('700', '언어', NULL); 
INSERT INTO CATEGORIES(CAT_ID, CAT_NAME, PARENT_ID) VALUES('710', '한국어', '700'); 
INSERT INTO CATEGORIES(CAT_ID, CAT_NAME, PARENT_ID) VALUES('720', '중국어', '700'); 
INSERT INTO CATEGORIES(CAT_ID, CAT_NAME, PARENT_ID) VALUES('730', '일본어·기타아시아제어', '700'); 
INSERT INTO CATEGORIES(CAT_ID, CAT_NAME, PARENT_ID) VALUES('740', '영어', '700'); 
INSERT INTO CATEGORIES(CAT_ID, CAT_NAME, PARENT_ID) VALUES('750', '독일어', '700'); 
INSERT INTO CATEGORIES(CAT_ID, CAT_NAME, PARENT_ID) VALUES('760', '프랑스어', '700'); 
INSERT INTO CATEGORIES(CAT_ID, CAT_NAME, PARENT_ID) VALUES('770', '스페인어·포르투갈어', '700'); 
INSERT INTO CATEGORIES(CAT_ID, CAT_NAME, PARENT_ID) VALUES('780', '이탈리아어', '700'); 
INSERT INTO CATEGORIES(CAT_ID, CAT_NAME, PARENT_ID) VALUES('790', '기타제어', '700'); 

INSERT INTO CATEGORIES(CAT_ID, CAT_NAME, PARENT_ID) VALUES('800', '문학', NULL); 
INSERT INTO CATEGORIES(CAT_ID, CAT_NAME, PARENT_ID) VALUES('810', '한국문학', '800'); 
INSERT INTO CATEGORIES(CAT_ID, CAT_NAME, PARENT_ID) VALUES('820', '중국문학', '800'); 
INSERT INTO CATEGORIES(CAT_ID, CAT_NAME, PARENT_ID) VALUES('830', '일본문학·기타아시아문학', '800'); 
INSERT INTO CATEGORIES(CAT_ID, CAT_NAME, PARENT_ID) VALUES('840', '영미문학', '800'); 
INSERT INTO CATEGORIES(CAT_ID, CAT_NAME, PARENT_ID) VALUES('850', '독일문학', '800'); 
INSERT INTO CATEGORIES(CAT_ID, CAT_NAME, PARENT_ID) VALUES('860', '프랑스문학', '800'); 
INSERT INTO CATEGORIES(CAT_ID, CAT_NAME, PARENT_ID) VALUES('870', '스페인·포르투갈문학', '800'); 
INSERT INTO CATEGORIES(CAT_ID, CAT_NAME, PARENT_ID) VALUES('880', '이탈리아문학', '800'); 
INSERT INTO CATEGORIES(CAT_ID, CAT_NAME, PARENT_ID) VALUES('890', '기타제문학', '800'); 

INSERT INTO CATEGORIES(CAT_ID, CAT_NAME, PARENT_ID) VALUES('900', '역사', NULL); 
INSERT INTO CATEGORIES(CAT_ID, CAT_NAME, PARENT_ID) VALUES('910', '아시아', '900'); 
INSERT INTO CATEGORIES(CAT_ID, CAT_NAME, PARENT_ID) VALUES('920', '유럽', '900'); 
INSERT INTO CATEGORIES(CAT_ID, CAT_NAME, PARENT_ID) VALUES('930', '아프리카', '900'); 
INSERT INTO CATEGORIES(CAT_ID, CAT_NAME, PARENT_ID) VALUES('940', '북아메리카', '900'); 
INSERT INTO CATEGORIES(CAT_ID, CAT_NAME, PARENT_ID) VALUES('950', '남아메리카', '900'); 
INSERT INTO CATEGORIES(CAT_ID, CAT_NAME, PARENT_ID) VALUES('960', '오세아니아', '900'); 
INSERT INTO CATEGORIES(CAT_ID, CAT_NAME, PARENT_ID) VALUES('970', '양극지방', '900'); 
INSERT INTO CATEGORIES(CAT_ID, CAT_NAME, PARENT_ID) VALUES('980', '지리', '900'); 
INSERT INTO CATEGORIES(CAT_ID, CAT_NAME, PARENT_ID) VALUES('990', '전기', '900'); 

SELECT *
FROM CATEGORIES;

COMMIT;
-- 커밋 완료
