SELECT USER
FROM DUAL;

--------------------------------------------------------------------------------
--[기본데이터 생성]
--------------------------------------------------------------------------------
INSERT INTO ROLE(ROLE_ID, ROLE_NAME) VALUES(SEQ_ROLE.NEXTVAL, '관리자');
INSERT INTO ROLE(ROLE_ID, ROLE_NAME) VALUES(SEQ_ROLE.NEXTVAL, '사서');
INSERT INTO ROLE(ROLE_ID, ROLE_NAME) VALUES(SEQ_ROLE.NEXTVAL, '회원');

SELECT *
FROM ROLE;

--==>>
/*
1	관리자
2	사서
3	회원
*/

INSERT INTO USER_STATUS(STATUS_ID, STATUS_NAME) VALUES(SEQ_USER_STATUS.NEXTVAL, '정상');
INSERT INTO USER_STATUS(STATUS_ID, STATUS_NAME) VALUES(SEQ_USER_STATUS.NEXTVAL, '연체정지');
INSERT INTO USER_STATUS(STATUS_ID, STATUS_NAME) VALUES(SEQ_USER_STATUS.NEXTVAL, '이용정지');

SELECT *
FROM USER_STATUS;

--==>>
/*
1	정상
2	연체정지
3	이용정지
*/
INSERT INTO BOOK_STATUS(BOOK_STATUS_ID, BOOK_STATUS_NAME) VALUES(SEQ_BOOK_STATUS.NEXTVAL, '대출가능');
INSERT INTO BOOK_STATUS(BOOK_STATUS_ID, BOOK_STATUS_NAME) VALUES(SEQ_BOOK_STATUS.NEXTVAL, '대출중');
INSERT INTO BOOK_STATUS(BOOK_STATUS_ID, BOOK_STATUS_NAME) VALUES(SEQ_BOOK_STATUS.NEXTVAL, '이용불가');


SELECT *
FROM BOOK_STATUS;
--==>>
/*
1	대출가능
2	대출중
3	이용불가
*/

INSERT INTO CATEGORIES(CAT_ID, CAT_NAME, PARENT_ID) VALUES('000', '총류', NULL); 
INSERT INTO CATEGORIES(CAT_ID, CAT_NAME, PARENT_ID) VALUES('010', '도서학·서지학', '000'); 
INSERT INTO CATEGORIES(CAT_ID, CAT_NAME, PARENT_ID) VALUES('020', '문헌정보학', '000'); 
INSERT INTO CATEGORIES(CAT_ID, CAT_NAME, PARENT_ID) VALUES('030', '백과사전', '000'); 
INSERT INTO CATEGORIES(CAT_ID, CAT_NAME, PARENT_ID) VALUES('040', '강연집·수필집', '000'); 
INSERT INTO CATEGORIES(CAT_ID, CAT_NAME, PARENT_ID) VALUES('050', '연속간행물', '000'); 
INSERT INTO CATEGORIES(CAT_ID, CAT_NAME, PARENT_ID) VALUES('060', '학회·단체', '000'); 
INSERT INTO CATEGORIES(CAT_ID, CAT_NAME, PARENT_ID) VALUES('070', '신문·언론', '000'); 
INSERT INTO CATEGORIES(CAT_ID, CAT_NAME, PARENT_ID) VALUES('080', '전집·총서', '000'); 
INSERT INTO CATEGORIES(CAT_ID, CAT_NAME, PARENT_ID) VALUES('090', '향토자료', '000'); 

INSERT INTO CATEGORIES(CAT_ID, CAT_NAME, PARENT_ID) VALUES('100', '철학', NULL); 
INSERT INTO CATEGORIES(CAT_ID, CAT_NAME, PARENT_ID) VALUES('110', '형이상학', '100'); 
INSERT INTO CATEGORIES(CAT_ID, CAT_NAME, PARENT_ID) VALUES('120', '인식론·인과론·인간학', '100'); 
INSERT INTO CATEGORIES(CAT_ID, CAT_NAME, PARENT_ID) VALUES('130', '철학의 체계', '100'); 
INSERT INTO CATEGORIES(CAT_ID, CAT_NAME, PARENT_ID) VALUES('140', '경학', '100'); 
INSERT INTO CATEGORIES(CAT_ID, CAT_NAME, PARENT_ID) VALUES('150', '동양철학·사상', '100'); 
INSERT INTO CATEGORIES(CAT_ID, CAT_NAME, PARENT_ID) VALUES('160', '서양철학', '100'); 
INSERT INTO CATEGORIES(CAT_ID, CAT_NAME, PARENT_ID) VALUES('170', '논리학', '100'); 
INSERT INTO CATEGORIES(CAT_ID, CAT_NAME, PARENT_ID) VALUES('180', '심리학', '100'); 
INSERT INTO CATEGORIES(CAT_ID, CAT_NAME, PARENT_ID) VALUES('190', '윤리학·도덕철학', '100'); 

INSERT INTO CATEGORIES(CAT_ID, CAT_NAME, PARENT_ID) VALUES('200', '종교', NULL); 
INSERT INTO CATEGORIES(CAT_ID, CAT_NAME, PARENT_ID) VALUES('210', '비교종료', '200'); 
INSERT INTO CATEGORIES(CAT_ID, CAT_NAME, PARENT_ID) VALUES('220', '불교', '200'); 
INSERT INTO CATEGORIES(CAT_ID, CAT_NAME, PARENT_ID) VALUES('230', '기독교', '200'); 
INSERT INTO CATEGORIES(CAT_ID, CAT_NAME, PARENT_ID) VALUES('240', '도교', '200'); 
INSERT INTO CATEGORIES(CAT_ID, CAT_NAME, PARENT_ID) VALUES('250', '천도교', '200'); 
INSERT INTO CATEGORIES(CAT_ID, CAT_NAME, PARENT_ID) VALUES('260', '신도', '200'); 
INSERT INTO CATEGORIES(CAT_ID, CAT_NAME, PARENT_ID) VALUES('270', '힌두교·브라만교', '200'); 
INSERT INTO CATEGORIES(CAT_ID, CAT_NAME, PARENT_ID) VALUES('280', '이슬람교(회교)', '200'); 
INSERT INTO CATEGORIES(CAT_ID, CAT_NAME, PARENT_ID) VALUES('290', '기타 제종교', '200'); 

INSERT INTO CATEGORIES(CAT_ID, CAT_NAME, PARENT_ID) VALUES('300', '사회과학', NULL); 
INSERT INTO CATEGORIES(CAT_ID, CAT_NAME, PARENT_ID) VALUES('310', '통계학', '300'); 
INSERT INTO CATEGORIES(CAT_ID, CAT_NAME, PARENT_ID) VALUES('320', '경제학', '300'); 
INSERT INTO CATEGORIES(CAT_ID, CAT_NAME, PARENT_ID) VALUES('330', '사회학·사회문제', '300'); 
INSERT INTO CATEGORIES(CAT_ID, CAT_NAME, PARENT_ID) VALUES('340', '정치학', '300'); 
INSERT INTO CATEGORIES(CAT_ID, CAT_NAME, PARENT_ID) VALUES('350', '행정학', '300'); 
INSERT INTO CATEGORIES(CAT_ID, CAT_NAME, PARENT_ID) VALUES('360', '법학', '300'); 
INSERT INTO CATEGORIES(CAT_ID, CAT_NAME, PARENT_ID) VALUES('370', '교육학', '300'); 
INSERT INTO CATEGORIES(CAT_ID, CAT_NAME, PARENT_ID) VALUES('380', '풍속·예절·민속학', '300'); 
INSERT INTO CATEGORIES(CAT_ID, CAT_NAME, PARENT_ID) VALUES('390', '국방·군사학', '300'); 

INSERT INTO CATEGORIES(CAT_ID, CAT_NAME, PARENT_ID) VALUES('400', '자연과학', NULL); 
INSERT INTO CATEGORIES(CAT_ID, CAT_NAME, PARENT_ID) VALUES('410', '수학', '400'); 
INSERT INTO CATEGORIES(CAT_ID, CAT_NAME, PARENT_ID) VALUES('420', '물리학', '400'); 
INSERT INTO CATEGORIES(CAT_ID, CAT_NAME, PARENT_ID) VALUES('430', '화학', '400'); 
INSERT INTO CATEGORIES(CAT_ID, CAT_NAME, PARENT_ID) VALUES('440', '천문학', '400'); 
INSERT INTO CATEGORIES(CAT_ID, CAT_NAME, PARENT_ID) VALUES('450', '지학', '400'); 
INSERT INTO CATEGORIES(CAT_ID, CAT_NAME, PARENT_ID) VALUES('460', '광물학', '400'); 
INSERT INTO CATEGORIES(CAT_ID, CAT_NAME, PARENT_ID) VALUES('470', '생명과학', '400'); 
INSERT INTO CATEGORIES(CAT_ID, CAT_NAME, PARENT_ID) VALUES('480', '식물학', '400'); 
INSERT INTO CATEGORIES(CAT_ID, CAT_NAME, PARENT_ID) VALUES('490', '동물학', '400');

INSERT INTO CATEGORIES(CAT_ID, CAT_NAME, PARENT_ID) VALUES('500', '기술과학', NULL); 
INSERT INTO CATEGORIES(CAT_ID, CAT_NAME, PARENT_ID) VALUES('510', '의학', '500'); 
INSERT INTO CATEGORIES(CAT_ID, CAT_NAME, PARENT_ID) VALUES('520', '농업·농학', '500'); 
INSERT INTO CATEGORIES(CAT_ID, CAT_NAME, PARENT_ID) VALUES('530', '공학·공업일반', '500'); 
INSERT INTO CATEGORIES(CAT_ID, CAT_NAME, PARENT_ID) VALUES('540', '건축공학', '500'); 
INSERT INTO CATEGORIES(CAT_ID, CAT_NAME, PARENT_ID) VALUES('550', '기계공학', '500'); 
INSERT INTO CATEGORIES(CAT_ID, CAT_NAME, PARENT_ID) VALUES('560', '전기·전자공학', '500'); 
INSERT INTO CATEGORIES(CAT_ID, CAT_NAME, PARENT_ID) VALUES('570', '화학공학', '500'); 
INSERT INTO CATEGORIES(CAT_ID, CAT_NAME, PARENT_ID) VALUES('580', '제조업', '500'); 
INSERT INTO CATEGORIES(CAT_ID, CAT_NAME, PARENT_ID) VALUES('590', '생활학', '500'); 

INSERT INTO CATEGORIES(CAT_ID, CAT_NAME, PARENT_ID) VALUES('600', '예술', NULL); 
INSERT INTO CATEGORIES(CAT_ID, CAT_NAME, PARENT_ID) VALUES('610', '건축물', '600'); 
INSERT INTO CATEGORIES(CAT_ID, CAT_NAME, PARENT_ID) VALUES('620', '조각·조형예술', '600'); 
INSERT INTO CATEGORIES(CAT_ID, CAT_NAME, PARENT_ID) VALUES('630', '공예·장식미술', '600'); 
INSERT INTO CATEGORIES(CAT_ID, CAT_NAME, PARENT_ID) VALUES('640', '서예', '600'); 
INSERT INTO CATEGORIES(CAT_ID, CAT_NAME, PARENT_ID) VALUES('650', '회화·도화', '600'); 
INSERT INTO CATEGORIES(CAT_ID, CAT_NAME, PARENT_ID) VALUES('660', '사진예술', '600'); 
INSERT INTO CATEGORIES(CAT_ID, CAT_NAME, PARENT_ID) VALUES('670', '음악', '600'); 
INSERT INTO CATEGORIES(CAT_ID, CAT_NAME, PARENT_ID) VALUES('680', '공연예술·매체예술', '600'); 
INSERT INTO CATEGORIES(CAT_ID, CAT_NAME, PARENT_ID) VALUES('690', '오락·스포츠', '600'); 

INSERT INTO CATEGORIES(CAT_ID, CAT_NAME, PARENT_ID) VALUES('700', '언어', NULL); 
INSERT INTO CATEGORIES(CAT_ID, CAT_NAME, PARENT_ID) VALUES('710', '한국어', '700'); 
INSERT INTO CATEGORIES(CAT_ID, CAT_NAME, PARENT_ID) VALUES('720', '중국어', '700'); 
INSERT INTO CATEGORIES(CAT_ID, CAT_NAME, PARENT_ID) VALUES('730', '일본어·기타아시아제어', '700'); 
INSERT INTO CATEGORIES(CAT_ID, CAT_NAME, PARENT_ID) VALUES('740', '영어', '700'); 
INSERT INTO CATEGORIES(CAT_ID, CAT_NAME, PARENT_ID) VALUES('750', '독일어', '700'); 
INSERT INTO CATEGORIES(CAT_ID, CAT_NAME, PARENT_ID) VALUES('760', '프랑스어', '700'); 
INSERT INTO CATEGORIES(CAT_ID, CAT_NAME, PARENT_ID) VALUES('770', '스페인어·포르투갈어', '700'); 
INSERT INTO CATEGORIES(CAT_ID, CAT_NAME, PARENT_ID) VALUES('780', '이탈리아어', '700'); 
INSERT INTO CATEGORIES(CAT_ID, CAT_NAME, PARENT_ID) VALUES('790', '기타제어', '700'); 

INSERT INTO CATEGORIES(CAT_ID, CAT_NAME, PARENT_ID) VALUES('800', '문학', NULL); 
INSERT INTO CATEGORIES(CAT_ID, CAT_NAME, PARENT_ID) VALUES('810', '한국문학', '800'); 
INSERT INTO CATEGORIES(CAT_ID, CAT_NAME, PARENT_ID) VALUES('820', '중국문학', '800'); 
INSERT INTO CATEGORIES(CAT_ID, CAT_NAME, PARENT_ID) VALUES('830', '일본문학·기타아시아문학', '800'); 
INSERT INTO CATEGORIES(CAT_ID, CAT_NAME, PARENT_ID) VALUES('840', '영미문학', '800'); 
INSERT INTO CATEGORIES(CAT_ID, CAT_NAME, PARENT_ID) VALUES('850', '독일문학', '800'); 
INSERT INTO CATEGORIES(CAT_ID, CAT_NAME, PARENT_ID) VALUES('860', '프랑스문학', '800'); 
INSERT INTO CATEGORIES(CAT_ID, CAT_NAME, PARENT_ID) VALUES('870', '스페인·포르투갈문학', '800'); 
INSERT INTO CATEGORIES(CAT_ID, CAT_NAME, PARENT_ID) VALUES('880', '이탈리아문학', '800'); 
INSERT INTO CATEGORIES(CAT_ID, CAT_NAME, PARENT_ID) VALUES('890', '기타제문학', '800'); 

INSERT INTO CATEGORIES(CAT_ID, CAT_NAME, PARENT_ID) VALUES('900', '역사', NULL); 
INSERT INTO CATEGORIES(CAT_ID, CAT_NAME, PARENT_ID) VALUES('910', '아시아', '900'); 
INSERT INTO CATEGORIES(CAT_ID, CAT_NAME, PARENT_ID) VALUES('920', '유럽', '900'); 
INSERT INTO CATEGORIES(CAT_ID, CAT_NAME, PARENT_ID) VALUES('930', '아프리카', '900'); 
INSERT INTO CATEGORIES(CAT_ID, CAT_NAME, PARENT_ID) VALUES('940', '북아메리카', '900'); 
INSERT INTO CATEGORIES(CAT_ID, CAT_NAME, PARENT_ID) VALUES('950', '남아메리카', '900'); 
INSERT INTO CATEGORIES(CAT_ID, CAT_NAME, PARENT_ID) VALUES('960', '오세아니아', '900'); 
INSERT INTO CATEGORIES(CAT_ID, CAT_NAME, PARENT_ID) VALUES('970', '양극지방', '900'); 
INSERT INTO CATEGORIES(CAT_ID, CAT_NAME, PARENT_ID) VALUES('980', '지리', '900'); 
INSERT INTO CATEGORIES(CAT_ID, CAT_NAME, PARENT_ID) VALUES('990', '전기', '900'); 

SELECT *
FROM CATEGORIES;
--==>> 데이터 삽입 완료

COMMIT;
-- 커밋 완료

--------------------------------------------------------------------------------
-- 도서 데이터 삽입
--------------------------------------------------------------------------------
-- 출판사 생성 PUBLISHERS(PUB_ID, PUB_NAME)
INSERT INTO PUBLISHERS(PUB_ID, PUB_NAME) VALUES (SEQ_PUBlISHER.NEXTVAL, '민음사');
INSERT INTO PUBLISHERS(PUB_ID, PUB_NAME) VALUES (SEQ_PUBlISHER.NEXTVAL, '창비');
INSERT INTO PUBLISHERS(PUB_ID, PUB_NAME) VALUES (SEQ_PUBlISHER.NEXTVAL, '문학동네');
INSERT INTO PUBLISHERS(PUB_ID, PUB_NAME) VALUES (SEQ_PUBlISHER.NEXTVAL, '을유문화사');
INSERT INTO PUBLISHERS(PUB_ID, PUB_NAME) VALUES (SEQ_PUBlISHER.NEXTVAL, '다산책방');
INSERT INTO PUBLISHERS(PUB_ID, PUB_NAME) VALUES (SEQ_PUBlISHER.NEXTVAL, '디플롯');
INSERT INTO PUBLISHERS(PUB_ID, PUB_NAME) VALUES (SEQ_PUBlISHER.NEXTVAL, '파란정원');
INSERT INTO PUBLISHERS(PUB_ID, PUB_NAME) VALUES (SEQ_PUBlISHER.NEXTVAL, '춤추는 고래');
INSERT INTO PUBLISHERS(PUB_ID, PUB_NAME) VALUES (SEQ_PUBlISHER.NEXTVAL, '미래엔');
INSERT INTO PUBLISHERS(PUB_ID, PUB_NAME) VALUES (SEQ_PUBlISHER.NEXTVAL, '위즈덤하우스');
INSERT INTO PUBLISHERS(PUB_ID, PUB_NAME) VALUES (SEQ_PUBlISHER.NEXTVAL, '문학과지성사');
INSERT INTO PUBLISHERS(PUB_ID, PUB_NAME) VALUES (SEQ_PUBlISHER.NEXTVAL, '정토');
INSERT INTO PUBLISHERS(PUB_ID, PUB_NAME) VALUES (SEQ_PUBlISHER.NEXTVAL, '곰');
INSERT INTO PUBLISHERS(PUB_ID, PUB_NAME) VALUES (SEQ_PUBlISHER.NEXTVAL, '동아시아');
INSERT INTO PUBLISHERS(PUB_ID, PUB_NAME) VALUES (SEQ_PUBlISHER.NEXTVAL, '이지스퍼블리싱');
INSERT INTO PUBLISHERS(PUB_ID, PUB_NAME) VALUES (SEQ_PUBlISHER.NEXTVAL, '빅피시');
INSERT INTO PUBLISHERS(PUB_ID, PUB_NAME) VALUES (SEQ_PUBlISHER.NEXTVAL, '황금가지');

SELECT *
FROM PUBLISHERS;


-- 작가 생성 AUTHORS(AUTHOR_ID, AUTHOR_NAME)
INSERT INTO AUTHORS(AUTHOR_ID, AUTHOR_NAME) VALUES (SEQ_AUTHOR.NEXTVAL, '헤르만 헤세');
INSERT INTO AUTHORS(AUTHOR_ID, AUTHOR_NAME) VALUES (SEQ_AUTHOR.NEXTVAL, '성해나');
INSERT INTO AUTHORS(AUTHOR_ID, AUTHOR_NAME) VALUES (SEQ_AUTHOR.NEXTVAL, '김애란');
INSERT INTO AUTHORS(AUTHOR_ID, AUTHOR_NAME) VALUES (SEQ_AUTHOR.NEXTVAL, '리처드 도킨스');
INSERT INTO AUTHORS(AUTHOR_ID, AUTHOR_NAME) VALUES (SEQ_AUTHOR.NEXTVAL, '브라이언 헤어');
INSERT INTO AUTHORS(AUTHOR_ID, AUTHOR_NAME) VALUES (SEQ_AUTHOR.NEXTVAL, '버네사 우즈');

SELECT *
FROM AUTHORS;


-- 도서정보 생성 BOOK_INFO(ISBN, TITLE, PUB_ID, CAT_ID)
INSERT INTO BOOK_INFO(ISBN, TITLE, PUB_ID, CAT_ID) VALUES (9788937460586, '싯다르타', 1, 850);
INSERT INTO BOOK_INFO(ISBN, TITLE, PUB_ID, CAT_ID) VALUES (9788936439743, '혼모노', 3, 810);
INSERT INTO BOOK_INFO(ISBN, TITLE, PUB_ID, CAT_ID) VALUES (8982819274, '고래', 4, 810);
INSERT INTO BOOK_INFO(ISBN, TITLE, PUB_ID, CAT_ID) VALUES (9788932473901, '이기적 유전자', 5, 470);
INSERT INTO BOOK_INFO(ISBN, TITLE, PUB_ID, CAT_ID) VALUES (9791197413025, '다정한 것이 살아남는다', 10, 180);

SELECT *
FROM BOOK_INFO;


