
--------------------------------------------------------------------------------
-- 프로시저를 통한 샘플 데이터 삽입
--------------------------------------------------------------------------------

-- 샘플데이터 삽입
--☆ 단독저자
DECLARE
    V_RESULT2 VARCHAR2(1000);
    V_RESULT VARCHAR2(100);
    V_MSG    VARCHAR2(500);
BEGIN
    -- 도서 및 작가 등록
    PRC_BOOK_TOTAL_REG('9791197437311', '백년 허리','내 허리 사용 설명서. 2, 치료편'
    , '언탱글링', '정선근', '510', V_RESULT2);


    -- 소장 도서 생성 (1권, 상태 1)
    PRC_BOOK_COPY_C('9791197437311',1, 1, V_RESULT, V_MSG);
    
    DBMS_OUTPUT.PUT_LINE('결과: ' || V_RESULT2 || ' / 소장메시지: ' || V_MSG);

END;
/

SET DEFINE OFF;

-- 부제없는 버전
DECLARE
    V_RESULT2 VARCHAR2(1000);
    V_RESULT VARCHAR2(100);
    V_MSG    VARCHAR2(500);
BEGIN
    -- 도서 및 작가 등록
    PRC_BOOK_TOTAL_REG('9788983710451', '파인만 씨, 농담도 잘하시네! 2',NULL
    , '사이언스북스', '리처드 파인만', '420', V_RESULT2);


    -- 소장 도서 생성 (1권, 상태 1)
    PRC_BOOK_COPY_C('9788983710451',1, 1, V_RESULT, V_MSG);
    
    DBMS_OUTPUT.PUT_LINE('결과: ' || V_RESULT2 || ' / 소장메시지: ' || V_MSG);

END;
/

-- 공동 저자 
DECLARE
    V_RESULT2 VARCHAR2(1000);
    V_RESULT VARCHAR2(100);
    V_MSG    VARCHAR2(500);
BEGIN
    -- 도서 및 작가 등록
    PRC_BOOK_TOTAL_REG('9788936452452', '바다에 미래가 있다','10대를 위한 해양과학 이야기'
    , '창비', '정찬주', '450', V_RESULT2);

END;
/

SELECT *
FROM VIEW_BOOK_INFO
ORDER BY BOOK_ID DESC;

select *
from book_info
where isbn ='9791193154069';

update book_info
set subtitle = '신의 탄생과 정신의 모험'
where isbn ='9791193154069';

select *
FROM BOOK_COPY;

delete
FROM BOOK_COPY
where book_id = 48;

DELETE
FROM BOOK_COPY
WHERE BOOK_ID=8;

SELECT *
FROM BOOK_INFO;

SELECT *
FROM PUBLISHERS;

INSERT INTO PUBLISHERS(PUB_ID, PUB_NAME)VALUES(SEQ_PUBlISHER.NEXTVAL, '교유서가');

SELECT *
FROM AUTHORS
ORDER BY AUTHOR_ID DESC;

INSERT INTO AUTHORS(AUTHOR_ID, AUTHOR_NAME)VALUES(SEQ_AUTHOR.NEXTVAL, '제임스 레이븐');

SELECT *
FROM CONTRIBUTOR;
INSERT INTO CONTRIBUTOR(CONTRIBUTOR_ID, ISBN, AUTHOR_ID, AUTHOR_ORDER)VALUES(SEQ_CONTRIBUTOR.NEXTVAL, '9791193710500' ,'45', 1 );
DELETE
FROM CONTRIBUTOR
WHERE CONTRIBUTOR_ID=54;


commit;


SELECT *
FROM USERS;

INSERT INTO USERS(USER_ID, LOGIN_ID, PW, NAME, BIRTH, GENDER, PHONE
, EMAIL, STATUS_ID, ROLE_ID, CREATED_AT, PENALTY_EDATE)
VALUES(SEQ_USER.NEXTVAL, 'admin', 'admin1234', '김관리자', TO_DATE('1975-05-25','YYYY-MM-DD'), 'F', '010-1111-1111'
, 'admin@test.com', 1, 1, SYSDATE, NULL);
INSERT INTO USERS(USER_ID, LOGIN_ID, PW, NAME, BIRTH, GENDER, PHONE
, EMAIL, STATUS_ID, ROLE_ID, CREATED_AT, PENALTY_EDATE)
VALUES(SEQ_USER.NEXTVAL, 'saseo', 'saseo1234', '박사서', TO_DATE('1999-09-01','YYYY-MM-DD'), 'F', '010-2222-2222'
, 'saseo@test.com', 1, 2, SYSDATE, NULL);
INSERT INTO USERS(USER_ID, LOGIN_ID, PW, NAME, BIRTH, GENDER, PHONE
, EMAIL, STATUS_ID, ROLE_ID, CREATED_AT, PENALTY_EDATE)
VALUES(SEQ_USER.NEXTVAL, 'superman', '12345', '강연체', TO_DATE('1998-07-15','YYYY-MM-DD'), 'M', '010-3333-3333'
, 'superman@test.com', 1, 3, SYSDATE, NULL);
INSERT INTO USERS(USER_ID, LOGIN_ID, PW, NAME, BIRTH, GENDER, PHONE
, EMAIL, STATUS_ID, ROLE_ID, CREATED_AT, PENALTY_EDATE)
VALUES(SEQ_USER.NEXTVAL, 'fullbook', '12345', '한다독', TO_DATE('1967-12-27','YYYY-MM-DD'), 'F', '010-4444-4444'
, 'ilovebook@test.com', 1, 3, SYSDATE, NULL);
INSERT INTO USERS(USER_ID, LOGIN_ID, PW, NAME, BIRTH, GENDER, PHONE
, EMAIL, STATUS_ID, ROLE_ID, CREATED_AT, PENALTY_EDATE)
VALUES(SEQ_USER.NEXTVAL, 'exttester', '12345', '나연장', TO_DATE('1991-05-14','YYYY-MM-DD'), 'M', '010-5555-5555'
, 'exttester@test.com', 1, 3, SYSDATE, NULL);
INSERT INTO USERS(USER_ID, LOGIN_ID, PW, NAME, BIRTH, GENDER, PHONE
, EMAIL, STATUS_ID, ROLE_ID, CREATED_AT, PENALTY_EDATE)
VALUES(SEQ_USER.NEXTVAL, 'sleeper', '12345', '이휴면', TO_DATE('2001-06-19','YYYY-MM-DD'), 'F', '010-6666-6666'
, 'sleeper@test.com', 1, 3, SYSDATE, NULL);
INSERT INTO USERS(USER_ID, LOGIN_ID, PW, NAME, BIRTH, GENDER, PHONE
, EMAIL, STATUS_ID, ROLE_ID, CREATED_AT, PENALTY_EDATE)
VALUES(SEQ_USER.NEXTVAL, 'blacklisted', '12345', '최정지', TO_DATE('1971-04-24','YYYY-MM-DD'), 'M', '010-7777-7777'
, 'blacklisted@test.com', 1, 3, SYSDATE, NULL);




/*
( P_BOOK_ID IN  BOOK_COPY.BOOK_ID%TYPE
, P_USER_ID IN  USERS.USER_ID%TYPE
, P_EXT_COUNT IN NUMBER DEFAULT 0
, O_RESULT  OUT VARCHAR2
, O_MSG OUT VARCHAR2
*/



update users
set name = '최패널티'
where user_id = 7;

SELECT *
FROM USERS;

/*
USER_ID 3 강연체 superman 12345
-- 대출을 하고 반납일이 지나 연체인 상황(아직 미반납 추가 대출 시도)

USER_ID 4 한다독 fullbook 12345
-- 10권을 모두 빌려 더 이상 대출할 수 없는 상황(추가 대출 시도)

USER_ID 5 나연장 extterster 12345
-- 대출한 책들을 모두 연장을 1번한 상태로 추가 연장하려고 하는 상황(추가 연장 시도)

USER_ID 6 이휴면 sleeper 12345
-- 대출한 책이 없고(내역은 있음) 유저상태가 이용정지인 유저의 로그인시도 상황


USER_ID 7 최패널티 blacklisted 12345
-- 이미 책은 모두 반납했고 아직 연체건에 대한 패널티 기간이 남아있는 상황(추가 대출 시도)
*/

SELECT BOOK_ID, TITLE, AUTHOR, PUB_NAME, ISBN
FROM VIEW_BOOK_INFO
WHERE BOOK_STATUS_ID = 1;

SELECT BOOK_ID, TITLE, AUTHOR, PUB_NAME, ISBN
FROM VIEW_BOOK_INFO
WHERE BOOK_STATUS_ID = 2;

SELECT *
FROM VIEW_BOOK_INFO;

SELECT *
FROM LOANS;

SELECT L.LOAN_ID, U.USER_ID, U.NAME 이름, L.BOOK_ID, BI.TITLE 제목
, L.LOAN_DATE 대출시작일, L.DUE_DATE 반납마감일
, L.RETURN_DATE 반납일
, L.EXT_COUNT 연장여부
, US.STATUS_NAME 유저상태, U.PENALTY_EDATE 
FROM LOANS L JOIN USERS U
ON L.USER_ID = U.USER_ID
    JOIN BOOK_COPY BC
ON BC.BOOK_ID = L.BOOK_ID
    JOIN BOOK_INFO BI
ON BC.ISBN = BI.ISBN
    JOIN USER_STATUS US
ON US.STATUS_ID = U.STATUS_ID
;

SELECT *
FROM BOOK_INFO;


DECLARE
    V_RESULT VARCHAR2(5000);
    V_MSG VARCHAR2(5000);
BEGIN
    PRC_LOANS_C('3','1',0, V_RESULT, V_MSG);
END;
/



