SELECT USER
FROM DUAL;

-- 소장 도서 생성 프로시저를 통해 삽입 해보기

DECLARE
    V_RESULT VARCHAR2(100);
    V_MSG    VARCHAR2(500);
BEGIN
    PRC_BOOK_COPY_C('9788937460586',1, 1, V_RESULT, V_MSG);
    
    DBMS_OUTPUT.PUT_LINE('결과: '|| V_RESULT);
    DBMS_OUTPUT.PUT_LINE('메시지: '|| V_MSG);

END;

VARIABLE V_RES VARCHAR2(100);
VARIABLE V_MSG VARCHAR2(500);

EXEC PRC_BOOK_COPY_C('9791197413025',2, O_RESULT=>:V_RES, O_MSG=>:V_MSG);

PRINT V_RES;
PRINT V_MSG;


-- 소장 도서 생성 프로시저 호출(ISBN, BOOK_STATUS_ID, BOOK_COUNT)
DECLARE
    V_RESULT VARCHAR2(100);
    V_MSG    VARCHAR2(500);
BEGIN
    PRC_BOOK_COPY_C('9791197918124',3, 1, V_RESULT, V_MSG);
    
    DBMS_OUTPUT.PUT_LINE('결과: '|| V_RESULT);
    DBMS_OUTPUT.PUT_LINE('메시지: '|| V_MSG);

END;

-- 대출 생성 프로시저 호출 

-- CREATE OR REPLACE PROCEDURE PRC_LOANS_C
--( P_BOOK_ID IN  BOOK_COPY.BOOK_ID%TYPE
--, P_USER_ID IN  USERS.USER_ID%TYPE
--, P_EXT_COUNT IN NUMBER DEFAULT 0
--, O_RESULT  OUT VARCHAR2
--, O_MSG OUT VARCHAR2
--)
-- PRC_LOANS_C
DECLARE
    V_RESULT VARCHAR2(1000);
    V_MSG VARCHAR2(1000);
BEGIN
    PRC_LOANS_C(1, 2, 0, V_RESULT, V_MSG);
END;


-- ○ 통합 샘플 데이터 생성 프로시저
CREATE OR REPLACE PROCEDURE PRC_BOOK_TOTAL_REG
(
  P_ISBN        IN BOOK_INFO.ISBN%TYPE,
  P_TITLE       IN BOOK_INFO.TITLE%TYPE,
  P_PUB_NAME    IN PUBLISHERS.PUB_NAME%TYPE,
  P_AUTHOR_NAME IN AUTHORS.AUTHOR_NAME%TYPE,
  P_CAT_ID      IN BOOK_INFO.CAT_ID%TYPE,
  O_RESULT      OUT VARCHAR2
)
IS
  V_PUB_ID    NUMBER;
  V_AUTHOR_ID NUMBER;
  V_COUNT     NUMBER;
BEGIN
  -- 1. 출판사 및 작가 등록 (기존과 동일)
  BEGIN
    SELECT PUB_ID INTO V_PUB_ID FROM PUBLISHERS WHERE PUB_NAME = P_PUB_NAME;
  EXCEPTION WHEN NO_DATA_FOUND THEN
    INSERT INTO PUBLISHERS (PUB_ID, PUB_NAME) VALUES (SEQ_PUBLISHER.NEXTVAL, P_PUB_NAME) RETURNING PUB_ID INTO V_PUB_ID;
  END;

  BEGIN
    SELECT AUTHOR_ID INTO V_AUTHOR_ID FROM AUTHORS WHERE AUTHOR_NAME = P_AUTHOR_NAME;
  EXCEPTION WHEN NO_DATA_FOUND THEN
    INSERT INTO AUTHORS (AUTHOR_ID, AUTHOR_NAME) VALUES (SEQ_AUTHOR.NEXTVAL, P_AUTHOR_NAME) RETURNING AUTHOR_ID INTO V_AUTHOR_ID;
  END;

  -- 2. 도서 기본 정보 등록
  SELECT COUNT(*) INTO V_COUNT FROM BOOK_INFO WHERE ISBN = P_ISBN;
  IF V_COUNT = 0 THEN
    INSERT INTO BOOK_INFO (ISBN, TITLE, PUB_ID, CAT_ID) VALUES (P_ISBN, P_TITLE, V_PUB_ID, P_CAT_ID);
  END IF;

  -- 3. 저자 매핑 (CONTRIBUTOR) 로직
  SELECT COUNT(*) INTO V_COUNT FROM CONTRIBUTOR WHERE ISBN = P_ISBN;

  IF V_COUNT = 0 THEN
    -- [첫 번째 저자] 일단 NULL로 입력
    INSERT INTO CONTRIBUTOR (CONTRIBUTOR_ID, ISBN, AUTHOR_ID, AUTHOR_ORDER)
    VALUES (SEQ_CONTRIBUTOR.NEXTVAL, P_ISBN, V_AUTHOR_ID, NULL);
  ELSE
    -- [두 번째 이상 저자] 
    -- 1) 기존에 NULL이었던 첫 번째 저자를 1로 업데이트 (처음 한 번만 실행됨)
    UPDATE CONTRIBUTOR SET AUTHOR_ORDER = 1 WHERE ISBN = P_ISBN AND AUTHOR_ORDER IS NULL;
    
    -- 2) 현재 저자를 순서에 맞게 입력 (현재 수 + 1)
    INSERT INTO CONTRIBUTOR (CONTRIBUTOR_ID, ISBN, AUTHOR_ID, AUTHOR_ORDER)
    VALUES (SEQ_CONTRIBUTOR.NEXTVAL, P_ISBN, V_AUTHOR_ID, V_COUNT + 1);
  END IF;

  O_RESULT := 'SUCCESS';
EXCEPTION
  WHEN OTHERS THEN
    O_RESULT := 'ERROR: ' || SQLERRM;
END;
/

