SELECT USER
FROM DUAL;

-- 출판사 생성 PUBLISHERS(PUB_ID, PUB_NAME)
INSERT INTO PUBLISHERS(PUB_ID, PUB_NAME) VALUES (SEQ_PUBlISHER.NEXTVAL, '민음사');
INSERT INTO PUBLISHERS(PUB_ID, PUB_NAME) VALUES (SEQ_PUBlISHER.NEXTVAL, '창비');
INSERT INTO PUBLISHERS(PUB_ID, PUB_NAME) VALUES (SEQ_PUBlISHER.NEXTVAL, '문학동네');
INSERT INTO PUBLISHERS(PUB_ID, PUB_NAME) VALUES (SEQ_PUBlISHER.NEXTVAL, '다산책방');
INSERT INTO PUBLISHERS(PUB_ID, PUB_NAME) VALUES (SEQ_PUBlISHER.NEXTVAL, '디플롯');

-- 출판사 수정 PUB_NAME
UPDATE PUBLISHERS SET PUB_NAME = '을유문화사' WHERE PUB_ID = 5;


SELECT *
FROM PUBLISHERS;
/*
1	민음사
3	창비
4	문학동네
5	을유문화사
9	다산책방
10	디플롯
*/

-- 작가 생성 AUTHORS(AUTHOR_ID, AUTHOR_NAME)
INSERT INTO AUTHORS(AUTHOR_ID, AUTHOR_NAME) VALUES (SEQ_AUTHOR.NEXTVAL, '헤르만 헤세');
INSERT INTO AUTHORS(AUTHOR_ID, AUTHOR_NAME) VALUES (SEQ_AUTHOR.NEXTVAL, '성해나');
INSERT INTO AUTHORS(AUTHOR_ID, AUTHOR_NAME) VALUES (SEQ_AUTHOR.NEXTVAL, '김애란');
INSERT INTO AUTHORS(AUTHOR_ID, AUTHOR_NAME) VALUES (SEQ_AUTHOR.NEXTVAL, '리처드 도킨스');
INSERT INTO AUTHORS(AUTHOR_ID, AUTHOR_NAME) VALUES (SEQ_AUTHOR.NEXTVAL, '브라이언 헤어');
INSERT INTO AUTHORS(AUTHOR_ID, AUTHOR_NAME) VALUES (SEQ_AUTHOR.NEXTVAL, '버네사 우즈');

-- 작가 수정 AUTHOR_NAME
UPDATE AUTHORS SET AUTHOR_NAME = '천명관' WHERE AUTHOR_ID = 3;


SELECT *
FROM AUTHORS;
/*
1	헤르만 헤세
2	성해나
3	천명관
4	리처드 도킨스
7	김애란
9	브라이언 헤어
10	버네사 우즈
*/



-- 도서정보 생성 BOOK_INFO(ISBN, TITLE, PUB_ID, CAT_ID)
INSERT INTO BOOK_INFO(ISBN, TITLE, PUB_ID, CAT_ID) VALUES (9788937460586, '싯다르타', 1, 850);
INSERT INTO BOOK_INFO(ISBN, TITLE, PUB_ID, CAT_ID) VALUES (9788936439743, '혼모노', 3, 810);
INSERT INTO BOOK_INFO(ISBN, TITLE, PUB_ID, CAT_ID) VALUES (8982819274, '고래', 4, 810);
INSERT INTO BOOK_INFO(ISBN, TITLE, PUB_ID, CAT_ID) VALUES (9788932473901, '이기적 유전자', 5, 470);
INSERT INTO BOOK_INFO(ISBN, TITLE, PUB_ID, CAT_ID) VALUES (9791197413025, '다정한 것이 살아남는다', 10, 180);

SELECT *
FROM BOOK_INFO;
/*
9788937460586	싯다르타	1	850
9788936439743	혼모노	    3	810
8982819274	    고래	    4	810
9788932473901	이기적 유전자	5	470
9791197413025	다정한 것이 살아남는다	10	180
*/

-- 도서정보 수정 TITLE, PUB_ID, CAT_ID
UPDATE BOOK_INFO SET TITLE = '이기적 유전자', PUB_ID = 5, CAT_ID = 470 WHERE ISBN  =9788932473901;


-- 이벤트 생성 LOAN_EVENTS(EVENT_ID, EVENT_NAME, START_DATE, END_DATE, MAX_LOAN_LIMIT)
INSERT INTO LOAN_EVENTS(EVENT_ID, EVENT_NAME, START_DATE, END_DATE, MAX_LOAN_LIMIT) VALUES (SEQ_LOAN_EVENT.NEXTVAL, '새학기 맞이 대출 두배', TO_DATE('2026-03-16','YYYY-MM-DD'), TO_DATE('2026-03-20', 'YYYY-MM-DD'), 20);

SELECT *
FROM LOAN_EVENTS;

-- 이벤트 수정 EVENT_NAME, START_DATE, END_DATE, MAX_LOAN_LIMIT
UPDATE LOAN_EVENTS SET EVENT_NAME = '봄 맞이 대출 두배' , START_DATE = TO_DATE('2026-03-01','YYYY-MM-DD'), END_DATE = TO_DATE('2026-03-08','YYYY-MM-DD'), MAX_LOAN_LIMIT = 20 WHERE EVENT_ID = 1;

-- 사용자 수정 USERS(USER_ID, LOGIN_ID, PW, NAME, BIRTH, GENDER, PHONE, EMAIL, STATUS_ID, ROLE_ID, CREATED_AT, PENALTY_EDATE)
-- PW, NAME, PHONE, EMAIL (사용자 직접 수정)
-- BIRTH, GENDER, STATUS_ID, ROLE_ID, PENALTY_EDATE (관리자 수정)
UPDATE USERS SET PW = '', PHONE = '', EMAIL = '' WHERE USER_ID = '';
UPDATE USERS SET PW = '', PHONE = '', EMAIL = '', STATUS_ID = , ROLE_ID = , PENALTY_EDATE = ? WHERE USER_ID = '';



-- 도서작가 생성 CONTRIBUTOR(CONTRIBUTOR_ID, ISBN, AUTHOR_ID, AUTHOR_ORDER)
INSERT INTO CONTRIBUTOR(CONTRIBUTOR_ID, ISBN, AUTHOR_ID, AUTHOR_ORDER) VALUES (SEQ_CONTRIBUTOR.NEXTVAL, 9788937460586, 1, NULL);
INSERT INTO CONTRIBUTOR(CONTRIBUTOR_ID, ISBN, AUTHOR_ID, AUTHOR_ORDER) VALUES (SEQ_CONTRIBUTOR.NEXTVAL, 9788936439743, 2, NULL);
INSERT INTO CONTRIBUTOR(CONTRIBUTOR_ID, ISBN, AUTHOR_ID, AUTHOR_ORDER) VALUES (SEQ_CONTRIBUTOR.NEXTVAL, 8982819274, 3, NULL);
INSERT INTO CONTRIBUTOR(CONTRIBUTOR_ID, ISBN, AUTHOR_ID, AUTHOR_ORDER) VALUES (SEQ_CONTRIBUTOR.NEXTVAL, 9788932473901, 4, NULL);

INSERT INTO CONTRIBUTOR(CONTRIBUTOR_ID, ISBN, AUTHOR_ID, AUTHOR_ORDER) VALUES (SEQ_CONTRIBUTOR.NEXTVAL, 9791197413025, 9, 1);
INSERT INTO CONTRIBUTOR(CONTRIBUTOR_ID, ISBN, AUTHOR_ID, AUTHOR_ORDER) VALUES (SEQ_CONTRIBUTOR.NEXTVAL, 9791197413025, 10, 2);


SELECT *
FROM CONTRIBUTOR;


/*
1	9788937460586	1	
2	9788936439743	2	
3	8982819274	    3	
4	9788932473901	4	
5	9791197413025	9	1
6	9791197413025	10	2
*/

-- 소장도서 수정 BOOK_COPY(BOOK_ID, ISBN, BOOK_STATUS_ID, CREATED_AT)
-- BOOK_STATUS_ID 대출중이 아닌 비활성화 상태일 때 필요
UPDATE BOOK_COPY SET BOOK_STATUS_ID = 3 WHERE BOOK_ID = ?;


-- 도서작가 수정 AUTHOR_ID, AUTHOR_ORDER (수정 대신 삭제후 생성이 나은가?)
-- 도서작가 삭제 (수정 대신 그 ISBN의 모든 데이터를 삭제한 후 다시 생성하도록 유도)
DELETE FROM CONTRIBUTOR WHERE ISBN = ? ;



--------------------------------------------------------------------------------
--------------------------------------------------------------------------------
-- ○ 출판사 생성 한줄
INSERT INTO PUBLISHERS(PUB_ID, PUB_NAME) VALUES (SEQ_PUBlISHER.NEXTVAL, ?)
;
-- ○ 출판사 수정 한줄
UPDATE PUBLISHERS SET PUB_NAME = ? WHERE PUB_ID = ?
;

-- ○ 작가 생성 한줄
INSERT INTO AUTHORS(AUTHOR_ID, AUTHOR_NAME) VALUES (SEQ_AUTHOR.NEXTVAL, ?)
;

-- ○ 작가 수정 한줄
UPDATE AUTHORS SET AUTHOR_NAME = ? WHERE AUTHOR_ID = ?
;

-- ○ 도서정보 생성 한줄
INSERT INTO BOOK_INFO(ISBN, TITLE, PUB_ID, CAT_ID) VALUES (?, ?, ?, ?)
;

-- ○ 도서정보 수정 한줄
UPDATE BOOK_INFO SET TITLE = ?, PUB_ID = ?, CAT_ID = ? WHERE ISBN = ?
;

-- ○ 이벤트 도서 생성 한줄
INSERT INTO LOAN_EVENTS(EVENT_ID, EVENT_NAME, START_DATE, END_DATE, MAX_LOAN_LIMIT) VALUES (SEQ_LOAN_EVENT.NEXTVAL, ?, TO_DATE(?,'YYYY-MM-DD'), TO_DATE(?, 'YYYY-MM-DD'), ?)
;

-- ○ 이벤트 도서 수정 한줄
UPDATE LOAN_EVENTS SET EVENT_NAME = ? , START_DATE = TO_DATE(?,'YYYY-MM-DD'), END_DATE = TO_DATE(?,'YYYY-MM-DD'), MAX_LOAN_LIMIT = ? WHERE EVENT_ID = ?
;

-- ○ 사용자 수정 일반 회원 버전 한줄
UPDATE USERS SET PW = ?, PHONE = ?, EMAIL = ? WHERE USER_ID = ?
;

-- ○ 사용자 수정 관리자 버전 한줄
UPDATE USERS SET PW = ?, PHONE = ?, EMAIL = ?, STATUS_ID = ?, ROLE_ID = ?, PENALTY_EDATE = ? WHERE USER_ID = ?
;

-- ○ 도서 작가 생성 한줄
INSERT INTO CONTRIBUTOR(CONTRIBUTOR_ID, ISBN, AUTHOR_ID, AUTHOR_ORDER) VALUES (SEQ_CONTRIBUTOR.NEXTVAL, ?, ?, ?)
;

-- ○ 도서 작가 삭제 한줄 (트랜잭션 처리 삭제와 다시 등록을 하나의 묶음으로 처리하기 그 후 커밋)
DELETE FROM CONTRIBUTOR WHERE ISBN = ?
;

-- ○ 소장 도서 수정 한줄
UPDATE BOOK_COPY SET BOOK_STATUS_ID = ? WHERE BOOK_ID = ?
;

--------------------------------------------------------------------------------
--------------------------------------------------------------------------------

SELECT *
FROM BOOK_COPY;


-- ● 도서 정보 뷰(도서명, isbn, 작가, 출판사, 카테고리, 책상태)
CREATE OR REPLACE VIEW VIEW_BOOK_INFO
AS
SELECT  NVL(C.BOOK_ID,-999) AS BOOK_ID
, I.TITLE
, NVL(LISTAGG(A.AUTHOR_NAME, ',') WITHIN GROUP(ORDER BY A.AUTHOR_NAME), '-') AS AUTHOR
, NVL(LISTAGG(A.AUTHOR_ID, ',') WITHIN GROUP(ORDER BY A.AUTHOR_ID), '-') AS AUTHOR_ID
, NVL(P.PUB_NAME,'-') AS PUB_NAME, NVL(CT.CAT_NAME, '-') AS CAT_NAME
, I.ISBN, NVL(BS.BOOK_STATUS_NAME, '-') AS BOOK_STATUS_NAME
, NVL(P.PUB_ID, -999) AS PUB_ID, NVL(CT.CAT_ID, -999) AS CAT_ID, NVL(C.BOOK_STATUS_ID, -999) AS BOOK_STATUS_ID
FROM BOOK_INFO I LEFT JOIN BOOK_COPY C
    ON I.ISBN = C.ISBN
LEFT JOIN PUBLISHERS P
    ON I.PUB_ID = P.PUB_ID
LEFT JOIN CATEGORIES CT
    ON I.CAT_ID = CT.CAT_ID
LEFT JOIN BOOK_STATUS BS
    ON C.BOOK_STATUS_ID = BS.BOOK_STATUS_ID
LEFT JOIN CONTRIBUTOR CR
    ON CR.ISBN = I.ISBN
LEFT JOIN AUTHORS A
    ON CR.AUTHOR_ID = A.AUTHOR_ID
GROUP BY C.BOOK_ID, I.TITLE, P.PUB_NAME, CT.CAT_NAME, I.ISBN, BS.BOOK_STATUS_NAME, P.PUB_ID, CT.CAT_ID, C.BOOK_STATUS_ID ;
    
SELECT *
FROM VIEW_BOOK_INFO;
    
SELECT *
FROM PUBLISHERS;


INSERT INTO BOOK_INFO(ISBN, TITLE, PUB_ID, CAT_ID) VALUES ('9791197918124', '보노보 핸드셰이크', 10, 490);

SELECT *
FROM BOOK_INFO;

SELECT *
FROM BOOK_COPY;

SELECT *
FROM USERS;

SELECT *
FROM ROLE;

INSERT INTO USERS(USER_ID, LOGIN_ID, PW, NAME, BIRTH, GENDER, PHONE, EMAIL
, STATUS_ID, ROLE_ID, CREATED_AT, PENALTY_EDATE)
VALUES(SEQ_USER.NEXTVAL, 'superman', '12345', '홍길동'
, TO_DATE('1994-02-05','YYYY-MM-DD'), 'F', '010-1234-1234', 'superman@super.com'
, 1, 3, SYSDATE, NULL); 
INSERT INTO USERS(USER_ID, LOGIN_ID, PW, NAME, BIRTH, GENDER, PHONE, EMAIL
, STATUS_ID, ROLE_ID, CREATED_AT, PENALTY_EDATE)
VALUES(SEQ_USER.NEXTVAL, 'batman', '12345', '이순신'
, TO_DATE('1971-04-24','YYYY-MM-DD'), 'M', '010-2345-2345', 'batman@bat.com'
, 1, 3, SYSDATE, NULL); 


INSERT INTO USERS(USER_ID, LOGIN_ID, PW, NAME, BIRTH, GENDER, PHONE, EMAIL
, STATUS_ID, ROLE_ID, CREATED_AT, PENALTY_EDATE)
VALUES(SEQ_USER.NEXTVAL, 'spiderman', '12345', '유관순'
, TO_DATE('2005-11-11','YYYY-MM-DD'), 'F', '010-1111-1111', 'spiderman@spider.com'
, 1, 3, SYSDATE, NULL); 

INSERT INTO USERS(USER_ID, LOGIN_ID, PW, NAME, BIRTH, GENDER, PHONE, EMAIL
, STATUS_ID, ROLE_ID, CREATED_AT, PENALTY_EDATE)
VALUES(SEQ_USER.NEXTVAL, 'admin', 'admin1234', '김관리자'
, TO_DATE('1986-05-19','YYYY-MM-DD'), 'F', '010-2222-2222', 'admin@admin.com'
, 1, 1, SYSDATE, NULL); 

INSERT INTO USERS(USER_ID, LOGIN_ID, PW, NAME, BIRTH, GENDER, PHONE, EMAIL
, STATUS_ID, ROLE_ID, CREATED_AT, PENALTY_EDATE)
VALUES(SEQ_USER.NEXTVAL, 'imsaseo', 'saseo1234', '최사서'
, TO_DATE('1999-09-01','YYYY-MM-DD'), 'M', '010-3333-3333', 'booklove@book.com'
, 1, 2, SYSDATE, NULL); 

INSERT INTO CONTRIBUTOR(CONTRIBUTOR_ID, ISBN, AUTHOR_ID, AUTHOR_ORDER) VALUES (SEQ_CONTRIBUTOR.NEXTVAL, '9791197918124', 9, NULL);    


-- ● 전체 대출 조회



SELECT * 
FROM LOANS;

UPDATE BOOK_COPY SET BOOK_STATUS_ID = 1 WHERE BOOK_ID = 2;

SELECT *
FROM BOOK_STATUS;

UPDATE BOOK_STATUS SET BOOK_STATUS_NAME = '대출가능' WHERE BOOK_STATUS_ID = 1;
UPDATE BOOK_STATUS SET BOOK_STATUS_NAME = '대출중' WHERE BOOK_STATUS_ID = 2;
UPDATE BOOK_STATUS SET BOOK_STATUS_NAME = '이용불가' WHERE BOOK_STATUS_ID = 3;


ALTER TABLE BOOK_STATUS 
MODIFY (BOOK_STATUS_NAME VARCHAR2(50));

ALTER TABLE USER_STATUS 
MODIFY (STATUS_NAME VARCHAR2(50));

UPDATE USER_STATUS SET STATUS_NAME = '정상' WHERE STATUS_ID = 1;
UPDATE USER_STATUS SET STATUS_NAME = '연체정지' WHERE STATUS_ID = 2;
UPDATE USER_STATUS SET STATUS_NAME = '이용정지' WHERE STATUS_ID = 3;
SELECT *
FROM USER_STATUS;

DESC BOOK_STATUS;

-- 현재 대출한 책(사용자 로그인 시 그 회원 건에 대해서)

-- 전체 대출된 책 목록




SELECT * FROM USERS;

SELECT *
FROM LOANS;



















