SELECT USER
FROM DUAL;

-- 출판사 생성 PUBLISHERS(PUB_ID, PUB_NAME)
INSERT INTO PUBLISHERS(PUB_ID, PUB_NAME) VALUES (SEQ_PUBlISHER.NEXTVAL, '민음사');
INSERT INTO PUBLISHERS(PUB_ID, PUB_NAME) VALUES (SEQ_PUBlISHER.NEXTVAL, '창비');
INSERT INTO PUBLISHERS(PUB_ID, PUB_NAME) VALUES (SEQ_PUBlISHER.NEXTVAL, '문학동네');
INSERT INTO PUBLISHERS(PUB_ID, PUB_NAME) VALUES (SEQ_PUBlISHER.NEXTVAL, '다산책방');
INSERT INTO PUBLISHERS(PUB_ID, PUB_NAME) VALUES (SEQ_PUBlISHER.NEXTVAL, '디플롯');



-- 출판사 수정 PUB_NAME
UPDATE PUBLISHERS SET PUB_NAME = '을유문화사' WHERE PUB_ID = 5;

SELECT *
FROM PUBLISHERS;
/*
1	민음사
3	창비
4	문학동네
5	을유문화사
9	다산책방
10	디플롯
*/

-- 작가 생성 AUTHORS(AUTHOR_ID, AUTHOR_NAME)
INSERT INTO AUTHORS(AUTHOR_ID, AUTHOR_NAME) VALUES (SEQ_AUTHOR.NEXTVAL, '헤르만 헤세');
INSERT INTO AUTHORS(AUTHOR_ID, AUTHOR_NAME) VALUES (SEQ_AUTHOR.NEXTVAL, '성해나');
INSERT INTO AUTHORS(AUTHOR_ID, AUTHOR_NAME) VALUES (SEQ_AUTHOR.NEXTVAL, '김애란');
INSERT INTO AUTHORS(AUTHOR_ID, AUTHOR_NAME) VALUES (SEQ_AUTHOR.NEXTVAL, '리처드 도킨스');
INSERT INTO AUTHORS(AUTHOR_ID, AUTHOR_NAME) VALUES (SEQ_AUTHOR.NEXTVAL, '브라이언 헤어');
INSERT INTO AUTHORS(AUTHOR_ID, AUTHOR_NAME) VALUES (SEQ_AUTHOR.NEXTVAL, '버네사 우즈');

-- 작가 수정 AUTHOR_NAME
UPDATE AUTHORS SET AUTHOR_NAME = '천명관' WHERE AUTHOR_ID = 3;


SELECT *
FROM AUTHORS;
/*
1	헤르만 헤세
2	성해나
3	천명관
4	리처드 도킨스
7	김애란
9	브라이언 헤어
10	버네사 우즈
*/



-- 도서정보 생성 BOOK_INFO(ISBN, TITLE, PUB_ID, CAT_ID)
INSERT INTO BOOK_INFO(ISBN, TITLE, PUB_ID, CAT_ID) VALUES (9788937460586, '싯다르타', 1, 850);
INSERT INTO BOOK_INFO(ISBN, TITLE, PUB_ID, CAT_ID) VALUES (9788936439743, '혼모노', 3, 810);
INSERT INTO BOOK_INFO(ISBN, TITLE, PUB_ID, CAT_ID) VALUES (8982819274, '고래', 4, 810);
INSERT INTO BOOK_INFO(ISBN, TITLE, PUB_ID, CAT_ID) VALUES (9788932473901, '이기적 유전자', 5, 470);
INSERT INTO BOOK_INFO(ISBN, TITLE, PUB_ID, CAT_ID) VALUES (9791197413025, '다정한 것이 살아남는다', 10, 180);

SELECT *
FROM BOOK_INFO;
/*
9788937460586	싯다르타	1	850
9788936439743	혼모노	    3	810
8982819274	    고래	    4	810
9788932473901	이기적 유전자	5	470
9791197413025	다정한 것이 살아남는다	10	180
*/

-- 도서정보 수정 TITLE, PUB_ID, CAT_ID
UPDATE BOOK_INFO SET TITLE = '이기적 유전자', PUB_ID = 5, CAT_ID = 470 WHERE ISBN  =9788932473901;


-- 이벤트 생성 LOAN_EVENTS(EVENT_ID, EVENT_NAME, START_DATE, END_DATE, MAX_LOAN_LIMIT)
INSERT INTO LOAN_EVENTS(EVENT_ID, EVENT_NAME, START_DATE, END_DATE, MAX_LOAN_LIMIT) VALUES (SEQ_LOAN_EVENT.NEXTVAL, '새학기 맞이 대출 두배', TO_DATE('2026-03-16','YYYY-MM-DD'), TO_DATE('2026-03-20', 'YYYY-MM-DD'), 20);

SELECT *
FROM LOAN_EVENTS;

-- 이벤트 수정 EVENT_NAME, START_DATE, END_DATE, MAX_LOAN_LIMIT
UPDATE LOAN_EVENTS SET EVENT_NAME = '봄 맞이 대출 두배' , START_DATE = TO_DATE('2026-03-01','YYYY-MM-DD'), END_DATE = TO_DATE('2026-03-08','YYYY-MM-DD'), MAX_LOAN_LIMIT = 20 WHERE EVENT_ID = 1;

-- 사용자 수정 USERS(USER_ID, LOGIN_ID, PW, NAME, BIRTH, GENDER, PHONE, EMAIL, STATUS_ID, ROLE_ID, CREATED_AT, PENALTY_EDATE)
-- PW, NAME, PHONE, EMAIL (사용자 직접 수정)
-- BIRTH, GENDER, STATUS_ID, ROLE_ID, PENALTY_EDATE (관리자 수정)
UPDATE USERS SET PW = '', PHONE = '', EMAIL = '' WHERE USER_ID = '';
UPDATE USERS SET PW = '', PHONE = '', EMAIL = '', STATUS_ID = , ROLE_ID = , PENALTY_EDATE = TO_DATE('','YYYY-MM-DD') WHERE USER_ID = '';



-- 도서작가 생성 CONTRIBUTOR(CONTRIBUTOR_ID, ISBN, AUTHOR_ID, AUTHOR_ORDER)
INSERT INTO CONTRIBUTOR(CONTRIBUTOR_ID, ISBN, AUTHOR_ID, AUTHOR_ORDER) VALUES (SEQ_CONTRIBUTOR.NEXTVAL, 9788937460586, 1, NULL);
INSERT INTO CONTRIBUTOR(CONTRIBUTOR_ID, ISBN, AUTHOR_ID, AUTHOR_ORDER) VALUES (SEQ_CONTRIBUTOR.NEXTVAL, 9788936439743, 2, NULL);
INSERT INTO CONTRIBUTOR(CONTRIBUTOR_ID, ISBN, AUTHOR_ID, AUTHOR_ORDER) VALUES (SEQ_CONTRIBUTOR.NEXTVAL, 8982819274, 3, NULL);
INSERT INTO CONTRIBUTOR(CONTRIBUTOR_ID, ISBN, AUTHOR_ID, AUTHOR_ORDER) VALUES (SEQ_CONTRIBUTOR.NEXTVAL, 9788932473901, 4, NULL);

INSERT INTO CONTRIBUTOR(CONTRIBUTOR_ID, ISBN, AUTHOR_ID, AUTHOR_ORDER) VALUES (SEQ_CONTRIBUTOR.NEXTVAL, 9791197413025, 9, 1);
INSERT INTO CONTRIBUTOR(CONTRIBUTOR_ID, ISBN, AUTHOR_ID, AUTHOR_ORDER) VALUES (SEQ_CONTRIBUTOR.NEXTVAL, 9791197413025, 10, 2);


SELECT *
FROM CONTRIBUTOR;
/*
1	9788937460586	1	
2	9788936439743	2	
3	8982819274	    3	
4	9788932473901	4	
5	9791197413025	9	1
6	9791197413025	10	2
*/

-- 소장도서 수정 BOOK_COPY(BOOK_ID, ISBN, BOOK_STATUS_ID, CREATED_AT)
-- BOOK_STATUS_ID 대출중이 아닌 비활성화 상태일 때 필요
UPDATE BOOK_COPY SET BOOK_STATUS_ID = 3 WHERE BOOK_ID = ?;


-- 도서작가 수정 AUTHOR_ID, AUTHOR_ORDER (수정 대신 삭제후 생성이 나은가?)
-- 도서작가 삭제 (수정 대신 그 ISBN의 모든 데이터를 삭제한 후 다시 생성하도록 유도)
DELETE FROM CONTRIBUTOR WHERE ISBN = ? ;



