CREATE TABLE ROLE
( ROLE_ID       NUMBER          NOT NULL
, ROLE_NAME     VARCHAR2(10)    NOT NULL
, CONSTRAINT    ROLE_ROLE_ID_PK PRIMARY KEY(ROLE_ID)
, CONSTRAINT    ROLE_ROLE_NAME_UK	UNIQUE(ROLE_NAME)
);

CREATE TABLE USER_STATUS
( STATUS_ID     NUMBER          NOT NULL
, STATUS_NAME   VARCHAR2(10)    NOT NULL
, CONSTRAINT    STATUS_STATUS_ID_PK PRIMARY KEY(STATUS_ID)
, CONSTRAINT    STATUS_STATUS_NAME_UK   UNIQUE(STATUS_NAME)
);

CREATE TABLE BOOK_STATUS
( BOOK_STATUS_ID    NUMBER          NOT NULL
, BOOK_STATUS_NAME  VARCHAR2(10)    NOT NULL
, CONSTRAINT BOOK_STATUS_ID_PK  PRIMARY KEY(BOOK_STATUS_ID)
, CONSTRAINT BOOK_STATUS_BOOK_STATUS_NAME_UK    UNIQUE(BOOK_STATUS_NAME)
);

CREATE TABLE PUBLISHERS
( PUB_ID    NUMBER          NOT NULL
, PUB_NAME  VARCHAR2(30)    NOT NULL
, CONSTRAINT PUBLISHERS_PUB_ID_PK   PRIMARY KEY(PUB_ID)   
, CONSTRAINT PUBLISHERS_PUB_NAME_UK	UNIQUE(PUB_NAME)
);

CREATE TABLE AUTHORS
( AUTHOR_ID     NUMBER          NOT NULL
, AUTHOR_NAME   VARCHAR2(30)    NOT NULL
, CONSTRAINT AUTHORS_AUTHOR_ID_PK    PRIMARY KEY(AUTHOR_ID)
, CONSTRAINT AUTHORS_AUTHOR_NAME_UK	 UNIQUE(AUTHOR_NAME)
);

CREATE TABLE CATEGORIES
( CAT_ID    NUMBER          NOT NULL
, CAT_NAME  VARCHAR2(10)    NOT NULL
, CONSTRAINT CATEGORIES_CAT_ID_PK PRIMARY KEY(CAT_ID)
, CONSTRAINT CATEGORIES_CAT_NAME_UK UNIQUE(CAT_NAME)
);

CREATE TABLE LOAN_EVENTS
( EVENT_ID          NUMBER          NOT NULL
, EVENT_NAME        VARCHAR2(30)    NOT NULL
, START_DATE        DATE            NOT NULL   
, END_DATE          DATE            NOT NULL
, MAX_LOAN_LIMIT    NUMBER(2)       NOT NULL
, CONSTRAINT LOAN_EVENTS_EVENT_ID_PK PRIMARY KEY(EVENT_ID)
);


CREATE TABLE USERS
( USER_ID       NUMBER          NOT NULL
, LOGIN_ID      VARCHAR2(30)    NOT NULL
, PW            VARCHAR2(30)    NOT NULL
, NAME          VARCHAR2(20)    NOT NULL
, BIRTH         DATE            NOT NULL
, GENDER        CHAR(1)         NOT NULL
, PHONE         VARCHAR2(13)    NOT NULL
, EMAIL         VARCHAR2(50)
, STATUS_ID     NUMBER          NOT NULL
, ROLE_ID       NUMBER          NOT NULL
, CREATED_AT    DATE            NOT NULL DEFAULT SYSDATE
, PENALTY_EDATE DATE    
, CONSTRAINT   USERS_USER_ID_PK PRIMARY KEY(USER_ID)
, CONSTRAINT   USERS_LOGIN_ID_UK    UNIQUE(LOGIN_ID)
, CONSTRAINT   USERS_EMAIL_UK       UNIQUE(EMAIL)	
, CONSTRAINT   USERS_STATUS_ID_FK   FOREIGN KEY(STATUS_ID)
            REFERENCES USER_STATUS(STATUS_ID)
, CONSTRAINT   USERS_ROLE_ID_FK   FOREIGN KEY(ROLE_ID)
            REFERENCES ROLE(ROLE_ID)            
);






























